BREAKS AGAIN: Edgar's qemu virtio-msg branch with Edgar's xen
FAILED: libcommon.a.p/hw_xen_xen-operations.c.o
aarch64-linux-gnu-gcc -Ilibcommon.a.p -Isubprojects/libvduse -I../../qemu-xen-arm64/subprojects/libvduse -I/usr/include/pixman-1 -I/usr/local/include -I/usr/include/glib-2.0 -I/usr/lib/aarch64-linux-gnu/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/gio-unix-2.0 -I/usr/include/slirp -fdiagnostics-color=auto -Wall -Winvalid-pch -Werror -std=gnu11 -O2 -g -fstack-protector-strong -Wempty-body -Wendif-labels -Wexpansion-to-defined -Wformat-security -Wformat-y2k -Wignored-qualifiers -Wimplicit-fallthrough=2 -Winit-self -Wmissing-format-attribute -Wmissing-prototypes -Wnested-externs -Wold-style-declaration -Wold-style-definition -Wredundant-decls -Wshadow=local -Wstrict-prototypes -Wtype-limits -Wundef -Wvla -Wwrite-strings -Wno-missing-include-dirs -Wno-psabi -Wno-shift-negative-value -isystem /prj/qemu-xen-arm64/linux-headers -isystem linux-headers -iquote . -iquote /prj/qemu-xen-arm64 -iquote /prj/qemu-xen-arm64/include -iquote /prj/qemu-xen-arm64/host/include/aarch64 -iquote /prj/qemu-xen-arm64/host/include/generic -iquote /prj/qemu-xen-arm64/tcg/aarch64 -pthread -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fno-strict-aliasing -fno-common -fwrapv -ftrivial-auto-var-init=zero -fzero-call-used-regs=used-gpr -fPIE -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -DNCURSES_WIDECHAR=1 -MD -MQ libcommon.a.p/hw_xen_xen-operations.c.o -MF libcommon.a.p/hw_xen_xen-operations.c.o.d -o libcommon.a.p/hw_xen_xen-operations.c.o -c ../../qemu-xen-arm64/hw/xen/xen-operations.c
../../qemu-xen-arm64/hw/xen/xen-operations.c:407:5: error: no previous prototype for 'xc_domain_gfn2mfn' [-Werror=missing-prototypes]
  407 | int xc_domain_gfn2mfn(xc_interface *xch,
      |     ^~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
ninja: build stopped: subcommand failed.
make: *** [Makefile:168: run-ninja] Error 1